services:
  - type: web
    name: ctrlchic-backend
    env: python
    region: oregon
    buildCommand: "cd backend && chmod +x build.sh && ./build.sh"
    startCommand: "cd backend && gunicorn ctrlchic.wsgi:application"
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: ctrlchic-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false

databases:
  - name: ctrlchic-db
    databaseName: ctrlchic
    plan: free
    region: oregon
